<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\PairSync.Domain\PairSync.Domain.csproj" />
    <ProjectReference Include="..\PairSync.SyncEngine\PairSync.SyncEngine.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Tmds.DBus.Protocol" />
  </ItemGroup>
</Project>
