// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PairSync.Storage;

#nullable disable

namespace PairSync.Storage.Migrations
{
    [DbContext(typeof(PairSyncDbContext))]
    [Migration("20260926151412_SyncProfiles")]
    partial class SyncProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PairSync.Domain.HistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FinishedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FinishedAtUtc");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.JobItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastWriteTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.HasIndex("JobId", "RelativePath")
                        .IsUnique();

                    b.ToTable("JobItems", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.PairedDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanSendToMe")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("PairedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Trust")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicKey")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.SyncActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Files")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Id");

                    b.ToTable("SyncActivities", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.SyncConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CopyIsLocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CopyPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocalMTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("LocalSha256")
                        .HasColumnType("BLOB");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteMTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RemoteSha256")
                        .HasColumnType("BLOB");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Resolved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Resolved");

                    b.ToTable("SyncConflicts", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.SyncFile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ChunkHashes")
                        .HasColumnType("BLOB");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Sha256")
                        .HasColumnType("BLOB");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "Side", "Path");

                    b.HasIndex("ProfileId", "Side", "Sequence");

                    b.ToTable("SyncFiles", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.SyncProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowWrite")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Excludes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSequence")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Paused")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Problem")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RemoteIndexId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteSequenceSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeerDeviceId");

                    b.ToTable("SyncProfiles", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.TransferJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PausedByPeer")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PeerDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Policy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("State", "PeerDeviceId");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("PairSync.Storage.ChunkJournalRecord", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunkSize")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Confirmed")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastWriteTimeUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TempPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransferId");

                    b.ToTable("ChunkJournal", (string)null);
                });

            modelBuilder.Entity("PairSync.Domain.JobItem", b =>
                {
                    b.HasOne("PairSync.Domain.TransferJob", null)
                        .WithMany("Items")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairSync.Domain.SyncActivity", b =>
                {
                    b.HasOne("PairSync.Domain.SyncProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairSync.Domain.SyncConflict", b =>
                {
                    b.HasOne("PairSync.Domain.SyncProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairSync.Domain.SyncFile", b =>
                {
                    b.HasOne("PairSync.Domain.SyncProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PairSync.Domain.TransferJob", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
