<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <Using Include="Xunit" />
    <ProjectReference Include="..\..\spikes\PairSync.Spike.Core\PairSync.Spike.Core.csproj" />
  </ItemGroup>
</Project>
